name: Arawak Films
favicon: null
layout_spectrum: 0.5677945544011891
typography_spectrum: 0.0847461111843586
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ee3e41'
    - '#0f1217'
    - '#f6a1a3'
    - '#c1bfc2'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
